const symbols = [
  "ADANIGREEN.NS", "ADANIPORTS.NS", "ASIANPAINT.NS", "AXISBANK.NS", 
  "BAJAJ-AUTO.NS", "BAJFINANCE.NS", "BHARTIARTL.NS", "BPCL.NS", 
  "CIPLA.NS", "COALINDIA.NS", "DIVISLAB.NS", "DRREDDY.NS", "EICHERMOT.NS", 
  "GRASIM.NS", "GAIL.NS", "HDFCBANK.NS", "HDFCLIFE.NS", "HDFC.NS", 
  "HCLTECH.NS", "ICICIBANK.NS", "INFY.NS", "INDUSINDBK.NS", "IOC.NS", 
  "ITC.NS", "JSWSTEEL.NS", "KOTAKBANK.NS", "LT.NS", "M&M.NS", "MARICO.NS", 
  "MARUTI.NS", "MCDOWELL-N.NS", "NTPC.NS", "ONGC.NS", "PIDILITIND.NS", 
  "POWERGRID.NS", "RECLTD.NS", "RELIANCE.NS", "SBIBANK.NS", "SBILIFE.NS", 
  "SAIL.NS", "SHREECEM.NS", "SUNPHARMA.NS", "TATACONSUM.NS", "TATAMOTORS.NS", 
  "TATAPOWER.NS", "TECHM.NS", "TCS.NS", "UPL.NS", "WIPRO.NS"
];



  export const nifty50Formatted = symbols.map(symbol => ({
    label: symbol
  }));
    
  export default symbols;
  